# Async adapter only works within the same process, so for manually triggering cable updates from a console,
# and seeing results in the browser, you must do so from the web console (running inside the dev process),
# not a terminal started via bin/rails console! Add "console" to any action or any ERB template view
# to make the web console appear.
development:
  adapter: async #Action Cable em processo (dev)

test:
  adapter: test #adapter de teste

production:
  adapter: solid_cable #Action Cable com Solid Cable
  connects_to:
    database:
      writing: cable #usa o banco cable
  polling_interval: 0.1.seconds #intervalo de polling
  message_retention: 1.day #quanto tempo guarda mensagem
