default: &default #bloco padrao do cache
  store_options:
    # Cap age of oldest cache entry to fulfill retention policies
    # max_age: <%= 60.days.to_i %>
    max_size: <%= 256.megabytes %> #tamanho maximo do cache
    namespace: <%= Rails.env %> #namespace por ambiente

development:
  <<: *default #herda default

test:
  <<: *default

production:
  database: cache #banco do Solid Cache
  <<: *default
