require "active_support/core_ext/integer/time" #helpers de tempo (2.days, etc.)

Rails.application.configure do #config so do ambiente development
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true #recarrega codigo ao salvar (sem reiniciar)

  # Do not eager load code on boot.
  config.eager_load = false #nao carrega tudo na subida (mais rapido no boot)

  # Show full error reports.
  config.consider_all_requests_local = true #mostra erro completo no browser/JSON

  # Enable server timing.
  config.server_timing = true #headers de timing para debug

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist? #se ativou cache de dev
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false #cache desligado por padrao
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store #cache em memoria

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local #uploads em disco local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false #nao estoura se e-mail falhar

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false #sem cache de templates de e-mail

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 } #host dos links de e-mail

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log #avisos de deprecacao no log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load #erro se migration pendente

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true #destaca origem das queries no log

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true #tags nas queries do log

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true #destaca jobs enfileirados no log

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true #destaca redirects no log

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true #anota views com o nome do arquivo

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true #erro se before_action apontar action inexistente

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
